# Generated by Django 4.2.3 on 2023-07-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_league_app', '0002_alter_club_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='stadium_id',
            new_name='stadium',
        ),
    ]
