# Generated by Django 4.2.3 on 2023-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_league_app', '0003_rename_stadium_id_club_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('telephone_code', models.TextField()),
                ('iso_2_code', models.TextField()),
                ('iso_3_code', models.TextField()),
                ('ensign', models.BinaryField(null=True)),
            ],
        ),
    ]
