# Generated by Django 4.2.3 on 2023-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_league_app', '0009_soccermatch_ft_result_soccermatch_ht_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.TextField(default=''),
        ),
    ]
