# Generated by Django 4.2.3 on 2023-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_league_app', '0010_club_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.TextField(),
        ),
    ]
