# Generated by Django 4.2.3 on 2023-07-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_league_app', '0011_alter_club_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/players/')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soccer_league_app.club')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soccer_league_app.nationality')),
            ],
        ),
    ]
