# Generated by Django 4.2.3 on 2023-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_league_app', '0012_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clothers_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
